#Port - If 0 get random port
server: 
 port: 0

#Component Info
info:
 component: Public-RestService
 
#Spring Application Name 
spring:
 application:
  name: Public-RestService
 cloud: 
  config:
   enabled: true
   uri: http://localhost:8888 


  
#Eureka Instance ID
eureka:
 instance:
  instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.int}}}
  leaseRenewalIntervalInSeconds: 5
  leaseExpirationDurationInSeconds: 15
  registerWithEureka: true
 client:
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5 
    
 
#Service Registration Method 
cloud:
 services:
  registrationMethod: route
  
#Disable HTTP Basic Authentication
security:
 basic:
  enabled: false