# HTTP Server
server: 
 port: 8761
 
 # Eureka Configuration Properties
eureka:
 client:
  registerWithEureka: false
  fetchRegistry: false
  healthcheck:
      enabled: true  
 server:
  waitTimeInMsWhenSyncEmpty: 0
  enableSelfPreservation: false